### PR TITLE
Add authentication support

### PR DESCRIPTION
**Pull request by dacr**
- Provide basic and bearer authentication capabilities.
- Enhance configuration strategy using a reference.conf file which provide default values
- Provide instructions about how to provide authentication configuration

### CODE REVIEW

**Comment by dacr** [comment]
So I only put changes related to authentication support. As this pull request provides a `reference.conf` file, I think you can remove the readSslFlag function from PrometheusClientConfig, as a `config.getBoolean("ssl")` will always succeed thanks to the default value `false` provided within the `reference.conf` file which is taken into account automatically by typesafe config.

**Comment by ex0ns** [comment]
Thanks for the update, I have one comment though: I don't really like having an implicit dependency on the order between the different type of authentication. Could you maybe raise an exception or at least add some logging if multiple authentication mechanisms are defined in the configuration file.

Otherwise, everything looks good

**Comment by dacr** [comment]
ok I'm going to improve this

**Comment by dacr** [comment]
done with logging

**Comment by Shastick** [comment]
Looking good to me. @ex0ns I'll try to get this through today :)

**Comment by Shastick** [comment]
Integrated via https://github.com/Sqooba/scala-promql-client/commit/feb2b479e1ecc493fac37d0e89336f45ced1a78a thanks again.

**Comment by Shastick** [comment]
Version 0.6.0 has been released to Sonatype, should be available within the next 24 hours.

**Pull request closed without merging**
